on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
      - run: cargo doc
      - name: Build wasm
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add wasm32-unknown-unknown
          CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="wasm-bindgen-test-runner" cargo +nightly test --target wasm32-unknown-unknown